name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker build -t "$IMAGE_TAG" .
          docker tag "$IMAGE_TAG" ${{ secrets.IMAGE_NAME }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.IMAGE_NAME }}:latest
